"""update schema: review and reaction

Revision ID: 4ab2c410dcf4
Revises: 532e25abebe7
Create Date: 2025-04-24 22:30:31.846099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab2c410dcf4'
down_revision: Union[str, None] = '532e25abebe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reaction_id'), 'reaction', ['id'], unique=False)
    op.drop_index('ix_review_review_id', table_name='review')
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.create_index('ix_review_review_id', 'review', ['id'], unique=False)
    op.drop_index(op.f('ix_reaction_id'), table_name='reaction')
    # ### end Alembic commands ###
