name: Deploy to Vercel

on:
  push:
    branches:
      - feat/code-base

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Vercel CLI
        run: |
          npm install -g vercel

      - name: Login to Vercel
        run: vercel login ${{ secrets.VERCEL_EMAIL }}
      
      - name: Deploy to Vercel
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deployment URL
        run: |
          echo "Deployment completed. View it here: https://<YOUR_PROJECT_NAME>.vercel.app"
