name: Deploy to Cloud Run

on:
  push:
    branches:
      - feat/code-base

jobs:
  deploy:
    name: 🚀 Deploy Toilet API to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-east1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: | 
          IMAGE=asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/toilet-api/toilet-api
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE ./Backend

      - name: Push Docker image to Artifact Registry
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy toilet-api \
            --image $IMAGE \
            --region asia-east1 \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}
            --service-account=githubcd@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
