name: Deploy to Cloud Run

on:
  push:
    branches:
      - feat/code-base

env:
  REGION: asia-east1
  SERVICE: toilet-api
  REPOSITORY: toilet-api
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE: asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/toilet-api/toilet-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker asia-east1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t $IMAGE ./Backend

      - name: Push Docker image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE }}
          region: ${{ env.REGION }}
