name: Deploy to Cloud Run

on:
  push:
    branches:
      - feat/code-base

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Set IMAGE name
        run: echo "IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/toilet-api:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE ./Backend

      - name: Push Docker image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy toilet-api \
            --image $IMAGE \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --port 8000
