name: Deploy to Cloud Run

on:
  push:
    branches:
      - feat/code-base  # 你的開發分支

jobs:
  deploy:
    name: 🚀 Deploy to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/toilet-api:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/toilet-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy toilet-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/toilet-api:latest \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --port 8000