name: 🚀 Deploy Nuxt Frontend to Vercel

on:
  push:
    branches:
      - feat/code-base
      - main
    paths:
      - 'Frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ✨ Deploy to Vercel
    steps:
      - name: 📆 Checkout Repo
        uses: actions/checkout@v3

      - name: ✨ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: 📦 Install dependencies
        run: npm install
        working-directory: Frontend

      - name: 🚀 Build project (optional if handled by Vercel)
        run: npm run build
        working-directory: Frontend

      - name: 🚜 Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./Frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}